### PR TITLE
WIP: Introduce bundled poco

### PR DESCRIPTION
**Pull request by tisonkun**

### CODE REVIEW

**Comment by leiysky** [comment]
Can this fix work with TiFlash?

**Comment by TisonKun** [comment]
> Can this fix work with TiFlash?

It is not yet ready for reviewing. Drop a pull request for running CI.

**Comment by leiysky** [comment]
> > Can this fix work with TiFlash?
> 
> It is not yet ready for reviewing. Drop a pull request for running CI.

That's fine. I tried to use a bundled poco in client-c, but found it would conflict with bundled poco of tics. Since we didn't have  strong demand on this then, I just stopped working on that.

FYI.

**Comment by TisonKun** [comment]
> > > Can this fix work with TiFlash?
> > 
> > 
> > It is not yet ready for reviewing. Drop a pull request for running CI.
> 
> That's fine. I tried to use a bundled poco in client-c, but found it would conflict with bundled poco of tics. Since we didn't have strong demand on this then, I just stopped working on that.
> 
> FYI.

Generally speaking we can suppress using bundled poco if there is one(e.g. provided by tics) present.

**Pull request closed without merging**
